application: popularity-contest
version: 1
runtime: python
api_version: 1
builtins:
- datastore_admin: on
handlers:
- url: /assets
  static_dir: assets
- url: /cron.*
  script: cron.py
  login: admin
- url: /tasks.*
  script: tasks.py
  login: admin
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: .*
  script: main.py